name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: init
      run: ./init.sh
    - name: make
      run: ./build.sh Debug main
    - name:
      run: ./test.sh
