name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v3
    - name: init
      run: ./init.sh

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: init
      run: ./init.sh
    - name: build
      run: ./build.sh Debug main

  test:
    runs-on: ubuntu-latest

    - name test:
      run: ./test.sh
